FROM crossbuild:base
RUN apt-get install -y -q \
 libstdc++-8-dev libwayland-dev libasound2-dev libpulse-dev libjack-dev libudev-dev libdbus-1-dev libibus-1.0-dev libxkbcommon-dev libegl1-mesa-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libxss-dev libxxf86vm-dev libgbm-dev libgles2-mesa-dev libvulkan-dev
