FROM crossbuild:base
RUN dpkg --add-architecture armhf && apt-get update && apt-get install -y -q \
 crossbuild-essential-armhf
RUN apt-get install -y -q \
 libstdc++-8-dev:armhf libwayland-dev:armhf libasound2-dev:armhf libpulse-dev:armhf libjack-dev:armhf libudev-dev:armhf libdbus-1-dev:armhf libibus-1.0-dev:armhf libxkbcommon-dev:armhf libegl1-mesa-dev:armhf libx11-dev:armhf libxcursor-dev:armhf libxext-dev:armhf libxi-dev:armhf libxinerama-dev:armhf libxrandr-dev:armhf libxss-dev:armhf libxxf86vm-dev:armhf libgbm-dev:armhf libgles2-mesa-dev:armhf libvulkan-dev:armhf
