FROM crossbuild:base
RUN dpkg --add-architecture arm64 && apt-get update && apt-get install -y -q \
 crossbuild-essential-arm64
RUN apt-get install -y -q \
 libstdc++-8-dev:arm64 libwayland-dev:arm64 libasound2-dev:arm64 libpulse-dev:arm64 libjack-dev:arm64 libudev-dev:arm64 libdbus-1-dev:arm64 libibus-1.0-dev:arm64 libxkbcommon-dev:arm64 libegl1-mesa-dev:arm64 libx11-dev:arm64 libxcursor-dev:arm64 libxext-dev:arm64 libxi-dev:arm64 libxinerama-dev:arm64 libxrandr-dev:arm64 libxss-dev:arm64 libxxf86vm-dev:arm64 libgbm-dev:arm64 libgles2-mesa-dev:arm64 libvulkan-dev:arm64
