FROM debian:buster-backports
ENV DEBIAN_FRONTEND noninteractive
RUN adduser builder
RUN apt-get update && apt-get upgrade -y && \
apt-get install --no-install-recommends -y -q \
 git-core vim-nox wget less nvi tmux lynx
RUN apt-get install -y -q \
 build-essential clang
