#! /bin/sh
set -e

script=$(readlink -f "$0")
script_path=$(dirname "$script")
. $script_path/detect

thirdparty=$HOME/crossbuild/thirdparty
src=$thirdparty/sdl2
obj=$HOME/crossbuild/build/$tag/sdl2

mkdir -p $obj
cd $obj

if [ ! -f $obj/Makefile -o "x$1" = "xconfig" ] ; then
	$src/configure \
	 --prefix=$HOME/crossbuild/local/$tag \
	 --host=$host \
	 --disable-shared \
	 --disable-render \
	 --enable-video-kmsdrm \
	 --disable-video-vulkan \
	#
fi

nice make -j 2
make install
