#! /bin/sh
set -e

script=$(readlink -f "$0")
script_path=$(dirname "$script")
. $script_path/detect

thirdparty=$HOME/crossbuild/thirdparty
src=$thirdparty/es2
obj=$HOME/crossbuild/build/$tag/es2

mkdir -p $obj
cd $obj

$host-gcc -O2 $archflags -c -o es2ld.o $src/es2ld.c
