#! /bin/sh
set -e

# no git submodules, as hello is just an example

thirdparty=$HOME/crossbuild/thirdparty

mkdir -p $thirdparty
cd $thirdparty

git clone https://github.com/efornara/sdl2

git clone --depth 1 https://github.com/nothings/stb
git clone --depth 1 --branch 0.9.9.8 https://github.com/g-truc/glm
